In [2]:
import numpy as np

In [3]:
a = [1,2,3]
b = [4,5,6]

In [4]:
na = np.array(a)
nb = np.array(b)

print(na+nb)

[5 7 9]


In [5]:
print(np.array([1,2,3]))
#Simple Array

[1 2 3]


In [6]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(np.full((2,3),9))

[[9 9 9]
 [9 9 9]]


In [9]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [10]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [11]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
print(arr.shape)

(2, 3)


In [14]:
print(arr.size)

6


In [15]:
print(arr.ndim)

2


In [16]:
print(arr.dtype)

int64


In [17]:
arr=np.array([10,20,30,40,50])

print(arr[0])
print(arr[-1])
print(arr[-2])
#iNDEXING
print("---")
print(arr[[0,1,3]])

10
50
40
---
[10 20 40]


In [18]:
#Slicing
arr=np.array([0,1,2,3,4,5,6,7,8])

print(arr[1:5])
print(arr[:3])
print(arr[3:])
print(arr[::2])
print(arr[::-1])
#negative slicing
print(arr[-3:])
print(arr[:-3])
print(arr[-4:-1])


[1 2 3 4]
[0 1 2]
[3 4 5 6 7 8]
[0 2 4 6 8]
[8 7 6 5 4 3 2 1 0]
[6 7 8]
[0 1 2 3 4 5]
[5 6 7]


In [19]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix[2,1])
print(matrix[1,2])
print(matrix[:1])
print("-----")
print(matrix[:-1])
print("-----")
print(matrix[0:2, 1:3])

8
6
[[1 2 3]]
-----
[[1 2 3]
 [4 5 6]]
-----
[[2 3]
 [5 6]]


Views

In [20]:
arr=np.array([10,20,30,40,50])

view = arr[1:4] #view = 20,30,40,50
view[0] = 100 #new view = 100, 30, 40, 50

print(view)
print(arr)

[100  30  40]
[ 10 100  30  40  50]


In [21]:
arr=np.array([10,20,30,40,50])
copy_arr = arr.copy()
print(copy_arr)

copy_arr[0] = 100
print("copy array : ",copy_arr)
print(arr)

[10 20 30 40 50]
copy array :  [100  20  30  40  50]
[10 20 30 40 50]


**Aggregration functions**

In [22]:
arr=np.array([[10,20,30,40,50],[10,20,30,40,50]])

print(arr.size)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

10
300
30.0
50
10
14.142135623730951


In [23]:
#AXIS
#axis 0 - rows
#axis 1 - cols

matrix = np.array([
    [1,2,3],
    [4,5,6], 
    [7,8,9]
])

print("Axis 1",np.sum(matrix, axis=1))
print("Axis 0",np.sum(matrix, axis=0))

Axis 1 [ 6 15 24]
Axis 0 [12 15 18]


**Reshaping**

In [24]:
arr = np.arange(1,13)
print(arr)

print(arr.reshape(3,4))
print("---")
print(arr.reshape(2,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

print(arr.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [26]:
print(np.arange(1,10))

print(np.random.rand(6))
print(np.random.rand(1,1000,20))

print(np.random.randint(1,1000,20))

[1 2 3 4 5 6 7 8 9]
[0.99971781 0.69590226 0.75419081 0.49420674 0.67096932 0.68045179]
[[[0.8445311  0.66212446 0.9848749  ... 0.39055729 0.92407482 0.97997686]
  [0.8177362  0.13836793 0.90554936 ... 0.79643736 0.21831985 0.16944596]
  [0.99534331 0.70024245 0.15998419 ... 0.11459521 0.29988646 0.6322549 ]
  ...
  [0.64900446 0.069869   0.96364673 ... 0.01999234 0.14389157 0.3420257 ]
  [0.08771879 0.57034218 0.8474347  ... 0.84991449 0.36403395 0.95528959]
  [0.03396087 0.92756173 0.94277063 ... 0.9675663  0.09295276 0.93744875]]]
[686 358 413 683   5 238 767 129 842 329 932 364 544  11 322 746 360 751
 683 643]


In [27]:
np.random.seed(45)
print(np.random.randint(1,1000,20))

[972 415 644 893 545 608 958 726 164 581 378 633  16 578 399 310 570 887
 457 216]


**Broadcasting**

In [28]:
arr = np.array([1,2,3])
print(arr+5)

[6 7 8]


In [29]:
matrix = np.array([
    [1,2,3],
    [4,5,6], 
    [7,8,9]
])

row = np. array([[10,20,30], [30,40,50], [50,60,70]])
print(matrix+row)

[[11 22 33]
 [34 45 56]
 [57 68 79]]


In [30]:
A = np.array([
    [1,2],
    [3,4]
])
print(A.T)

[[1 3]
 [2 4]]


In [31]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A.shape)

(2, 2)


In [32]:
print(A*B)     #dot product - element wise mutiplication
print("---")
print(A@B)     #matrix multiplication

[[ 5 12]
 [21 32]]
---
[[19 22]
 [43 50]]


In [33]:
arr = np.array([True, False, True])

print(np.all(arr))     #checks if every value is true
print(np.any(arr))     #at least one value is true

False
True


In [34]:
marks = np.array([40,80,30,90])
print(np.where(marks>50, "Pass", "Fail"))

['Fail' 'Pass' 'Fail' 'Pass']


In [35]:
a = np.array([1,2])
b = np.array([3,4])

print(a)
print(b)

[1 2]
[3 4]


In [36]:
print(np.concatenate((a,b)))

[1 2 3 4]


In [37]:
print(np.stack((a,b)))

[[1 2]
 [3 4]]


In [38]:
print(np.hstack((a,b)))

[1 2 3 4]


In [39]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [40]:
arr = np.array([1.948572895723985239875389472387,2.8,3.7])
print(arr)

[1.9485729 2.8       3.7      ]


In [41]:
print(arr.dtype)
print(arr.astype(int))
print(arr.astype(np.float32))

float64
[1 2 3]
[1.9485729 2.8       3.7      ]


In [42]:
arr = np.arange(100)
print(arr.nbytes)

800


In [43]:
arr = np.array([1,2,3])

print(np.append(arr, 4))    #add at the end
print(np.insert(arr, 0, 1000))      #insert at specific posn
print(np.delete(arr,1))   #to delete

[1 2 3 4]
[1000    1    2    3]
[1 3]


In [44]:
arr = np.array([10, 50, 60, 67 ])
print(np.sort(arr))
print(np.argmax(arr))
print(np.argmin(arr))

[10 50 60 67]
3
0


In [45]:
arr = np.array([1.0,4.6,2,9.3,16.1])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.floor(arr))
print(np.ceil(arr))

print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.mean(arr))

[1.         2.14476106 1.41421356 3.04959014 4.01248053]
[0.         1.5260563  0.69314718 2.2300144  2.77881927]
[2.71828183e+00 9.94843156e+01 7.38905610e+00 1.09380192e+04
 9.82067092e+06]
[ 1.  4.  2.  9. 16.]
[ 1.  5.  2. 10. 17.]
4.6
30.812000000000005
5.5508557898760085
6.6
